parameters:
  k0:
    bounds: [20, 35]
  delta:
    bounds: [0.5, 0.65]
  beta:
    bounds: [0.04, 0.24]
  p_ref:
    bounds: [10, 90]
  ref_conc:
    fixed_value: 0.14

PSO:
  n_particles: 300 # Increases computation time
  n_iterations: 20 # Increases computation time
  inertia_weight: 0.6 #  Common values are in the range of [0.4, 0.9].
  topology: random # star, ring
  optimizer: global # global, local
  cognitive_parameter: 2
  social_parameter: 2

reference_profiles:
  # Define the probes to use in the objective function calculation
  - name: Probe 0 (z = 0.5cm)
    path: ./fixtures/validation/RochaData/exp/z=0,5cm.csv
    height: 0.005 # meters
  - name: Probe 1 (z = 2.0cm)
    path: ./fixtures/validation/RochaData/exp/z=2,0cm.csv
    height: 0.02 # meters

simulation:
  sim_name: estimation_simulation
  domain:
    height: 0.21
    spatial_divisions: 220
  suspension:
    initial_conc: 0.1391
    max_conc: 0.2
  solid_phase:
    particle_diam: 0.0000408
    particle_esphericity: 0.8
    density: 2709
  fluid_phase:
    density: 891.4
    power_law:
      M: 30.13
      n: 0.21
  simulation_parameters:
    timestep: 1000
    total_time: 31536000
  export:
    frequency: 100
  report:
    frequency: 1000
