sim_name: stepped_domain
domain:
  height: 0.21
  spatial_divisions: 220
  annular_domain:
    internal_radius: 0.01
    steps:
      - position_z: 0.05
        radius: 0.05
      - position_z: 0.1
        radius: 0.1
      - position_z: 0.15
        radius: 0.12
      - position_z: 0.21
        radius: 0.15
suspension:
  initial_conc: 0.1391
  max_conc: 0.19
solid_phase:
  particle_diam: 0.0000408
  particle_esphericity: 0.8
  density: 2709
fluid_phase:
  density: 891.4
  power_law:
    M: 30.13
    n: 0.21
simulation_parameters:
  timestep: 1000
  total_time: 31536000
equation_parameters:
  delta: 0.58
  k0: 27.99
  beta: 0.19
  ref_conc: 0.14
  p_ref: 18.62
export:
  frequency: 100
report:
  frequency: 1000
